version: '3.8'

services:
  mermaid_dianaz:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8510:8510"
    volumes:
      - .:/app
    container_name: mermaid_dianaz
    environment:
      - GIT_PYTHON_REFRESH=quiet
